#!/usr/bin/env python3
"""
Shared DansLab (MMBAI) brand furniture for the Markdown reports under results/.

Every report this repo publishes ships as a bilingual pair — `<BASE>_EN.md` and
`<BASE>_ES.md` — and opens with the same header block: the logo raster, the
`DANSLAB · MMBAI` kicker, and the language switch. Generators call
`brand_header()` instead of pasting that block, so a change here (or in
`brand/tokens.json`) propagates to every report on the next build.

Brand rules live in `brand/BRAND-GUIDE.md`; the token values in
`brand/tokens.json`. Do not introduce colors, fonts or wording outside them.

Usage from a generator:

    from report_brand import LANGS, brand_header, brand_footer

    for lang in LANGS:                      # ("en", "es")
        parts  = brand_header(out_dir, lang, "README")
        parts += ...body...
        parts += brand_footer(lang)
"""
from __future__ import annotations

import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BRAND_DIR = REPO_ROOT / "brand"
BRAND_TOKENS = BRAND_DIR / "tokens.json"
LOGO_REPORT = BRAND_DIR / "assets" / "danslab-logo-report.png"

#: Report languages, in the order they should be generated. English first —
#: it is the default reading of any lab artifact; Spanish always ships with it.
LANGS = ("en", "es")

#: The one-line organisation kicker, per language. Kept identical in structure
#: so the two reports line up visually.
KICKER = {
    "en": "**DANSLAB · MMBAI** — Molecular Modeling, Bioinformatics & AI · "
          "Universidad de la República, Salto, Uruguay",
    "es": "**DANSLAB · MMBAI** — Modelado Molecular, Bioinformática e IA · "
          "Universidad de la República, Salto, Uruguay",
}

#: Language switch. Both labels appear in both languages, by brand convention
#: ("both languages always move together").
SWITCH_EN = "Read in English"
SWITCH_ES = "Leer en español"

FOOTER = {
    "en": "_DansLab · MMBAI — Universidad de la República, Salto, Uruguay. "
          "Generated by this repo's report builders; edit the generator, not the Markdown._",
    "es": "_DansLab · MMBAI — Universidad de la República, Salto, Uruguay. "
          "Generado por los builders de reportes de este repo; editar el generador, no el Markdown._",
}


def tokens() -> dict:
    """Canonical brand token values (colors, fonts, grid, logo rules)."""
    return json.loads(BRAND_TOKENS.read_text())


def logo_relpath(report_dir: Path) -> str:
    """POSIX-style relative path from `report_dir` to the report logo raster."""
    rel = os.path.relpath(LOGO_REPORT, start=Path(report_dir).resolve())
    return Path(rel).as_posix()


def brand_header(report_dir: Path, lang: str, base: str = "REPORT") -> list[str]:
    """
    Markdown lines for the brand header block.

    report_dir  Directory the report will be written to (fixes the logo path).
    lang        "en" or "es".
    base        Report basename without the language suffix, e.g. "README" or
                "REPORT" — used to build the language-switch links.
    """
    if lang not in LANGS:
        raise ValueError(f"lang must be one of {LANGS}, got {lang!r}")
    return [
        f"![]({logo_relpath(report_dir)})",
        "",
        KICKER[lang],
        "",
        f"*[{SWITCH_EN}]({base}_EN.md) · [{SWITCH_ES}]({base}_ES.md)*",
        "",
    ]


def brand_footer(lang: str) -> list[str]:
    """Markdown lines closing a report: a rule plus the brand attribution."""
    if lang not in LANGS:
        raise ValueError(f"lang must be one of {LANGS}, got {lang!r}")
    return ["---", "", FOOTER[lang], ""]


def out_path(report_dir: Path, lang: str, base: str = "REPORT") -> Path:
    """`<report_dir>/<base>_EN.md` or `_ES.md`."""
    return Path(report_dir) / f"{base}_{lang.upper()}.md"
